## Operations on Tensors in Tensorflow
* Aim is to understand how to perform different operations using tensors to accomplish some tasks
* A simple example:
  * Assume that a model is built and target values are predicted (y_pred). Your goal is to understand the loss or error between predicted (y_pred) and actual values (y_actual)

In [1]:
import tensorflow as tf
# Fetch the version of tensorflow
tf.__version__

'2.8.2'

In [2]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
# randomly select y_actual
y_actual = tf.constant([2,3,5,6])

print("y_actual before 1-hot", y_actual)
#perform one hot encoding on y_actual
y_actual = tf.one_hot(y_actual, depth =10)

print("y_actual after 1-hot", y_actual)

y_actual before 1-hot tf.Tensor([2 3 5 6], shape=(4,), dtype=int32)
y_actual after 1-hot tf.Tensor(
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]], shape=(4, 10), dtype=float32)


In [4]:
# select y_pred values
y_pred = tf.random.uniform([4,10])
print("y_pred :", y_pred)

y_pred : tf.Tensor(
[[0.3541777  0.72831166 0.31223857 0.41495943 0.803514   0.18450129
  0.22171986 0.03670311 0.9106679  0.7802657 ]
 [0.71365    0.158319   0.68827176 0.86321294 0.47074175 0.5483179
  0.16350067 0.21273696 0.37356007 0.73895025]
 [0.6567911  0.6192061  0.47360528 0.9873625  0.23843229 0.54379535
  0.4702798  0.7792349  0.91831124 0.34046078]
 [0.15204287 0.7541716  0.99353313 0.26622403 0.99606586 0.55762994
  0.51941144 0.839854   0.10632646 0.3840555 ]], shape=(4, 10), dtype=float32)


In [5]:
from tensorflow import keras
# calculate mean square error (MSE)

error_mse = tf.keras.losses.mse(y_actual, y_pred)
print(error_mse)
# calculate mean of MSE
error_mse_mean = tf.reduce_mean(error_mse)

print(error_mse_mean)

tf.Tensor([0.34693998 0.23066242 0.40665293 0.40480977], shape=(4,), dtype=float32)
tf.Tensor(0.34726626, shape=(), dtype=float32)


## Little complex operations on tesnors
* Create a neural network
* A linear layer with input of two samples & four features x[2,4], and three output nodes will have weight matrix of size 4x3, and bias matrix of size 3x1
* A neural network without activation function is linear layer (more about activation funcstions later)


In [6]:
x = tf.random.normal([2,4]) # A tensor with 2 samples and 4 features
print("x : ", x)
w = tf.ones([4,3])
print("w : ", w)
b = tf.zeros([3])
print("b : ", b)

y_out = x@w+b
print("y_out : ", y_out)


x :  tf.Tensor(
[[-0.97048277  2.0229337  -1.65035    -1.3001783 ]
 [ 0.3378257   0.6225424  -2.0361242  -0.38325104]], shape=(2, 4), dtype=float32)
w :  tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)
b :  tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
y_out :  tf.Tensor(
[[-1.8980772 -1.8980772 -1.8980772]
 [-1.4590071 -1.4590071 -1.4590071]], shape=(2, 3), dtype=float32)


## Indexing & slicing of tensors
* perform indexing and slicing of tensors

In [7]:
# Create a 4D tensor
x = tf.random.normal([4,2,2,3])
x.shape

TensorShape([4, 2, 2, 3])

In [8]:
x

<tf.Tensor: shape=(4, 2, 2, 3), dtype=float32, numpy=
array([[[[-0.3230516 , -1.0916394 , -1.8347666 ],
         [-0.80987495, -0.37976754, -1.1398672 ]],

        [[-0.8812354 , -0.94815177, -0.14900249],
         [-1.4797202 , -0.42984676, -0.62546927]]],


       [[[ 0.2890467 , -0.2620646 , -0.3367134 ],
         [ 0.04814572,  1.5613844 ,  0.68977034]],

        [[-0.05607104, -0.92558265,  0.41893306],
         [-0.24384752,  1.8544422 ,  1.3832917 ]]],


       [[[ 0.31312555,  0.06972736,  0.9896064 ],
         [-1.8790739 ,  0.19990905, -1.0325323 ]],

        [[ 0.6521822 , -0.47155833,  0.6335867 ],
         [-2.3384979 ,  0.76320964,  0.08218677]]],


       [[[-0.7945317 ,  0.75980216, -0.8334125 ],
         [-0.8393843 , -0.34644535,  0.18831012]],

        [[ 0.5100716 , -1.0025319 ,  0.9435986 ],
         [-0.21775243,  0.882667  ,  1.203207  ]]]], dtype=float32)>

In [19]:
x[1][0]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.2890467 , -0.2620646 , -0.3367134 ],
       [ 0.04814572,  1.5613844 ,  0.68977034]], dtype=float32)>

In [9]:
x[2][0][1][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.19990905>

In [10]:
# extract the first element in x
x[0]

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-0.3230516 , -1.0916394 , -1.8347666 ],
        [-0.80987495, -0.37976754, -1.1398672 ]],

       [[-0.8812354 , -0.94815177, -0.14900249],
        [-1.4797202 , -0.42984676, -0.62546927]]], dtype=float32)>

In [11]:
# extract the last element in x
x[3]

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-0.7945317 ,  0.75980216, -0.8334125 ],
        [-0.8393843 , -0.34644535,  0.18831012]],

       [[ 0.5100716 , -1.0025319 ,  0.9435986 ],
        [-0.21775243,  0.882667  ,  1.203207  ]]], dtype=float32)>

In [12]:
# extract the last element in x
x[-1]

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-0.7945317 ,  0.75980216, -0.8334125 ],
        [-0.8393843 , -0.34644535,  0.18831012]],

       [[ 0.5100716 , -1.0025319 ,  0.9435986 ],
        [-0.21775243,  0.882667  ,  1.203207  ]]], dtype=float32)>

In [13]:
# Fetch the second row of the first 4d tensor:
x[0][1]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.8812354 , -0.94815177, -0.14900249],
       [-1.4797202 , -0.42984676, -0.62546927]], dtype=float32)>

In [14]:
# Fetch the second row and second column of the first 4-d tensor:
x[0][1][1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-1.4797202 , -0.42984676, -0.62546927], dtype=float32)>

In [15]:
# Fetch the second column and second column of the first 4-d tensor:
x[0][1][:1]

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.8812354 , -0.94815177, -0.14900249]], dtype=float32)>

In [16]:
# Fetch the second column and second column of the first 4-d tensor:
x[0][1][:,2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.14900249, -0.62546927], dtype=float32)>