## Keras is a high-level API to use Tensorflow for neural network model development.
* If you are running the Tensorflow & Keras on your local desktop/laptop/server, use the following two steps to install tensorflow, followed by Keras

### *Step 1:* Current stable release of Tensroflow for CPU and GPU
```pip install tensorflow```

### *Step 2:* Import Keras after Tensorflow installation is successful in the last step
```from tensorflow import keras```



## Exercise 1
* Create a neural network model using Keras to add two numers

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
# data preparation

# create numpy array with two arrays of 1000 random values
x= np.array([np.random.randint(low=2, high=500, size=1000), np.random.randint(low=2, high=500, size=1000)])

# add the two arrays and append it to previously defined numpy array and transpose it
x = np.append(x, [x[0] + x[1]]).reshape(3,1000).T

# convert numpy array to a tensor
x_tensor = tf.convert_to_tensor(x)

In [4]:
x_tensor[654]

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([302, 482, 784])>

In [9]:
# separate training inputs and training targets
x_train   = x_tensor[:,0:2]
x_targets = x_tensor[:,2:3]

# normalise the data
#from tensorflow.keras.layers import Normalization

#normalizer = Normalization(axis=-1)
#normalizer.adapt(x_tensor)

#normalized_data = normalizer(x_tensor)

# separate training inputs and training targets
#x_train   = normalized_data[:,0:2]
#x_targets = normalized_data[:,2:3]


In [5]:
print("Data without normalization")
print(x_tensor[:,0:2][0])
print(x_tensor[:,2:3][0])

#print("Data with normalization")
#print(x_train[0])
#print(x_targets[0])

Data without normalization
tf.Tensor([423  77], shape=(2,), dtype=int64)
tf.Tensor([500], shape=(1,), dtype=int64)


In [6]:
# model construction

# import models and layers modules from keras package
from keras import models
from keras import layers

# create a neural networks of eight neurons in first layer and one neuron in the second layer
add_two_model = models.Sequential()
add_two_model.add(layers.Dense(8, activation='relu', input_shape=(2,)))
add_two_model.add(layers.Dense(1, activation='linear', name = 'out'))

In [7]:
# compile model using loss as MAE
add_two_model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

# check the summary of the model
add_two_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 24        
                                                                 
 out (Dense)                 (None, 1)                 9         
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


In [10]:
# train the model
add_two_model.fit(x_train, x_targets, batch_size=32, epochs = 100)

Epoch 1/100
32/32 [==============================] - 3s 2ms/step - loss: 505.8985 - mae: 505.8985
Epoch 2/100
32/32 [==============================] - 0s 2ms/step - loss: 473.4653 - mae: 473.4653
Epoch 3/100
32/32 [==============================] - 0s 2ms/step - loss: 437.0100 - mae: 437.0100
Epoch 4/100
32/32 [==============================] - 0s 2ms/step - loss: 393.3069 - mae: 393.3069
Epoch 5/100
32/32 [==============================] - 0s 2ms/step - loss: 339.9386 - mae: 339.9386
Epoch 6/100
32/32 [==============================] - 0s 2ms/step - loss: 273.2577 - mae: 273.2577
Epoch 7/100
32/32 [==============================] - 0s 2ms/step - loss: 190.5732 - mae: 190.5732
Epoch 8/100
32/32 [==============================] - 0s 2ms/step - loss: 116.6985 - mae: 116.6985
Epoch 9/100
32/32 [==============================] - 0s 2ms/step - loss: 77.7241 - mae: 77.7241
Epoch 10/100
32/32 [==============================] - 0s 2ms/step - loss: 56.8201 - mae: 56.8201
Epoch 11/100
32/32 [===

In [ ]:
# validating model
test_set = np.array([[3.3, 30], [4.5, 10.5], [11.1,10.1], [2.9,10.1],[5.9,9.1], [14,104]])
print(add_two_model.predict(test_set))

[[ 33.252514]
 [ 14.979662]
 [ 21.178564]
 [ 12.980628]
 [ 14.98128 ]
 [117.845665]]


In [ ]:
# validating model
test_set = np.array([[0.3, 0.79], [0.5, 1.58], [1.1,2.20], [.9,2.1],[.09,.01], [1.4,1.04]])
print(add_two_model.predict(test_set))

[[1.0843861 ]
 [2.0732238 ]
 [3.2922    ]
 [2.992391  ]
 [0.04416748]
 [2.4337573 ]]


In [11]:
test_set = np.array([[20, 0.76], 
                     [10, 0.69], 
                     [85, 4.76],
                     [9, 10.7]
                     ]
                    )
print(add_two_model.predict(test_set))

[[20.73046 ]
 [10.667634]
 [89.682945]
 [19.675863]]


In [12]:
test_set = np.array([[20070, 56031],
                     [-10, -55]
                     ]
                    )
print(add_two_model.predict(test_set))

[[7.6060789e+04]
 [3.5686834e+00]]


In [13]:
7.6060789*10**4

76060.789

In [14]:
20070+56031

76101