## Exercise 2
* Create a neural network model using Keras to multiply two matrices

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [2]:
# data preparation

#set random seed to generate same random numbers to repeat the results
import random
random.seed(365)

#create NumPy matrix A of size 2x2 filled with random integers between 0 and 100
matA=np.random.randint(0, 100, (2, 2))

#create NumPy matrix B of size 2x2 filled with random integers between 0 and 100
matB=np.random.randint(0, 100, (2, 2))

# perform matrix multiplication
matAB = np.matmul(matA,matB)

#flatten the values of matrix A into array
x_train = matA.flatten()

#flatten values of matrix B into array, and append with matrix A in training data
x_train = np.append(x_train, matB.flatten())

#flatten values of matrix AB into array for target of training data
x_targets = matAB.flatten()

# use a for loop to generate 100 matrices of A and B, multiply them and plug them into train and target sets 
for i in range(1000):
  matA=np.random.randint(0, 100, (2, 2))
  matB=np.random.randint(0, 100, (2, 2))
  matAB = np.matmul(matA,matB)
  x_train = np.append(x_train, np.array([matA.flatten(), matB.flatten()]))
  x_targets = np.append(x_targets, matAB.flatten())

print(x_train.size)
print(x_targets.size)

# reshapte train and test sets to make them suitable for building neural network model
x_train = x_train.reshape(1001,8)
x_targets = x_targets.reshape(1001,4)

# convert numpy array to a tensor
x_train_tensor = tf.convert_to_tensor(x_train)
x_targets_tensor = tf.convert_to_tensor(x_targets)

8008
4004


In [3]:
print(x_train_tensor[0])
print(x_targets_tensor[0])

tf.Tensor([84 77 34 73 81 36 99 73], shape=(8,), dtype=int64)
tf.Tensor([14427  8645  9981  6553], shape=(4,), dtype=int64)


In [4]:
# multiply and verify the results
41*23+75*96 # first element of matrix multiplication

8143

In [5]:
# Min Max Scaling 
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
x_train_tensor_scaled = mms.fit_transform(x_train_tensor)
mms_target = MinMaxScaler()
x_targets_tensor_scaled = mms_target.fit_transform(x_targets_tensor)

In [6]:
x_train_tensor = tf.keras.utils.normalize(x_train_tensor)
x_targets_tensor = tf.keras.utils.normalize(x_targets_tensor)
print(x_train_tensor[0])
print(x_targets_tensor[0])

tf.Tensor(
[0.40776699 0.37378641 0.16504854 0.35436893 0.39320388 0.17475728
 0.48058252 0.35436893], shape=(8,), dtype=float64)
tf.Tensor([0.699457   0.41913119 0.48390381 0.31770581], shape=(4,), dtype=float64)


In [8]:
# model construction

# import models and layers modules from keras package
from keras import models
from keras import layers

# create a neural networks of eight neurons in first layer and one neuron in the second layer
matmul_two_model = models.Sequential()
matmul_two_model.add(layers.Dense(16, activation='relu', input_shape=(8,)))
matmul_two_model.add(layers.Dense(16, activation='relu'))
matmul_two_model.add(layers.Dense(32, activation='relu'))
matmul_two_model.add(layers.Dense(64, activation='relu'))
# matmul_two_model.add(layers.Dense(128, activation='relu'))
# matmul_two_model.add(layers.Dense(128, activation='relu'))
# matmul_two_model.add(layers.Dense(256, activation='relu'))
# matmul_two_model.add(layers.Dense(256, activation='relu'))
# matmul_two_model.add(layers.Dense(128, activation='relu'))
# matmul_two_model.add(layers.Dense(64, activation='relu'))
# matmul_two_model.add(layers.Dense(32, activation='relu'))
# matmul_two_model.add(layers.Dense(16, activation='relu'))
# matmul_two_model.add(layers.Dense(4, activation='linear', name = 'out'))
matmul_two_model.add(layers.Dense(4, activation='relu', name = 'out'))

In [9]:
# compile model using loss as MAE
matmul_two_model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mean_absolute_error'])


# check the summary of the model
matmul_two_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 16)                144       
                                                                 
 dense_1 (Dense)             (None, 16)                272       
                                                                 
 dense_2 (Dense)             (None, 32)                544       
                                                                 
 dense_3 (Dense)             (None, 64)                2112      
                                                                 
 out (Dense)                 (None, 4)                 260       
                                                                 
Total params: 3,332
Trainable params: 3,332
Non-trainable params: 0
_________________________________________________________________


In [10]:
# train the model
# matmul_two_model.fit(x_train_tensor, x_targets_tensor, batch_size=16, epochs = 50)
matmul_two_model.fit(x_train_tensor_scaled, x_targets_tensor, epochs = 50)

Epoch 1/50
32/32 [==============================] - 3s 3ms/step - loss: 0.1925 - mean_absolute_error: 0.1925
Epoch 2/50
32/32 [==============================] - 0s 3ms/step - loss: 0.1585 - mean_absolute_error: 0.1585
Epoch 3/50
32/32 [==============================] - 0s 3ms/step - loss: 0.1349 - mean_absolute_error: 0.1349
Epoch 4/50
32/32 [==============================] - 0s 3ms/step - loss: 0.1150 - mean_absolute_error: 0.1150
Epoch 5/50
32/32 [==============================] - 0s 3ms/step - loss: 0.1021 - mean_absolute_error: 0.1021
Epoch 6/50
32/32 [==============================] - 0s 3ms/step - loss: 0.0918 - mean_absolute_error: 0.0918
Epoch 7/50
32/32 [==============================] - 0s 3ms/step - loss: 0.0848 - mean_absolute_error: 0.0848
Epoch 8/50
32/32 [==============================] - 0s 3ms/step - loss: 0.0793 - mean_absolute_error: 0.0793
Epoch 9/50
32/32 [==============================] - 0s 3ms/step - loss: 0.0732 - mean_absolute_error: 0.0732
Epoch 10/50
32/32 [

In [11]:
#inspect the model
#matmul_two_model.get_weights();

In [12]:
# validating model
test_set = np.array([[3.3, 30, 4.5, 10.5, 11.1,10.1, 2.9,10.1]])
# test_set= tf.keras.utils.normalize(tf.convert_to_tensor(test_set))
#print(matmul_two_model.predict(test_set))

In [13]:
test_set = np.array([[3.3, 30, 4.5, 10.5, 11.1,10.1, 2.9,10.1]])
test_set_scaled = mms.transform(test_set)
prediction_test = matmul_two_model.predict(test_set_scaled)
print(mms_target.inverse_transform(prediction_test))

[[6298.3833 8888.362  3358.46   6170.248 ]]


## Challenge 
Improve the accuracy by changing the number of neurons and layers of the neural networks