## Import packages and set the default values for random values generation, epochs and batch size

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import to_categorical
import numpy as np
import logging

tf.get_logger().setLevel(logging.ERROR)
tf.random.set_seed(7)
EPOCHS = 20
BATCH_SIZE = 1

## Load and Prepare the Training and Test Datasets

In [2]:
# Load training and test datasets.
mnist = keras.datasets.mnist
(train_images, train_labels), (test_images,
                               test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
# Standardize the data.
mean = np.mean(train_images)
stddev = np.std(train_images)
train_images = (train_images - mean) / stddev
test_images = (test_images - mean) / stddev

In [4]:
type(train_labels)

numpy.ndarray

In [5]:
train_labels[0:5]

array([5, 0, 4, 1, 9], dtype=uint8)

In [6]:
# One-hot encode labels.
train_labels = to_categorical(train_labels, num_classes=10)
test_labels = to_categorical(test_labels, num_classes=10)

## Create the Neural Network

In [7]:
# Object used to initialize weights.
initializer = keras.initializers.RandomUniform(
    minval=-0.1, maxval=0.1)
# Create a Sequential model.
# 784 inputs.
# Two Dense (fully connected) layers with 25 and 10 neurons.
# tanh as activation function for hidden layer.
# Logistic (sigmoid) as activation function for output layer.
model = keras.Sequential([
keras.layers.Flatten(input_shape=(28, 28)), 
keras.layers.Dense(25, activation='tanh', kernel_initializer=initializer, bias_initializer='zeros'), 
keras.layers.Dense(10, activation='sigmoid', kernel_initializer=initializer, bias_initializer='zeros')])

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 25)                19625     
                                                                 
 dense_1 (Dense)             (None, 10)                260       
                                                                 
Total params: 19,885
Trainable params: 19,885
Non-trainable params: 0
_________________________________________________________________


In [9]:
#model = sequential()
#model.add(Dense(25, activation='tanh', kernel_initializer=initializer, bias_initializer='zeros'))
#model.add(Dense(10, activation='sigmoid', kernel_initializer=initializer, 
               # bias_initializer='zeros')])

IndentationError: ignored

## Train the network

In [10]:
# Use stochastic gradient descent (SGD) with
# learning rate of 0.01 and no other bells and whistles.
# MSE as loss function and report accuracy during training.
opt = keras.optimizers.SGD(learning_rate=0.01)
# adam optimizer --> opt = 'adam'
model.compile(loss='mean_squared_error', optimizer = opt, metrics =['accuracy'])
# Train the model for 20 epochs.
# Shuffle (randomize) order.
# Update weights after each example (batch_size=1).
history = model.fit(train_images, train_labels,
                    validation_data=(test_images, test_labels),
                    epochs=EPOCHS, batch_size=BATCH_SIZE,
                    verbose=2, shuffle=True)

Epoch 1/20
60000/60000 - 96s - loss: 0.0493 - accuracy: 0.7168 - val_loss: 0.0242 - val_accuracy: 0.9007 - 96s/epoch - 2ms/step
Epoch 2/20
60000/60000 - 92s - loss: 0.0200 - accuracy: 0.9038 - val_loss: 0.0165 - val_accuracy: 0.9185 - 92s/epoch - 2ms/step
Epoch 3/20
60000/60000 - 92s - loss: 0.0158 - accuracy: 0.9161 - val_loss: 0.0143 - val_accuracy: 0.9238 - 92s/epoch - 2ms/step
Epoch 4/20
60000/60000 - 92s - loss: 0.0141 - accuracy: 0.9230 - val_loss: 0.0132 - val_accuracy: 0.9256 - 92s/epoch - 2ms/step
Epoch 5/20
60000/60000 - 91s - loss: 0.0130 - accuracy: 0.9279 - val_loss: 0.0124 - val_accuracy: 0.9286 - 91s/epoch - 2ms/step
Epoch 6/20
60000/60000 - 91s - loss: 0.0123 - accuracy: 0.9312 - val_loss: 0.0119 - val_accuracy: 0.9317 - 91s/epoch - 2ms/step
Epoch 7/20
60000/60000 - 91s - loss: 0.0117 - accuracy: 0.9340 - val_loss: 0.0115 - val_accuracy: 0.9333 - 91s/epoch - 2ms/step
Epoch 8/20
60000/60000 - 91s - loss: 0.0113 - accuracy: 0.9365 - val_loss: 0.0112 - val_accuracy: 0.9343

In [11]:
test_predictons = model.predict(test_images).flatten()

313/313 [==============================] - 1s 1ms/step


In [12]:
test_predictons[0:50]

array([2.63371598e-03, 1.85060210e-03, 1.09801935e-02, 2.86532845e-02,
       6.42480329e-04, 2.90209637e-03, 2.88128354e-06, 9.98083353e-01,
       7.97398970e-05, 4.59156139e-03, 5.51721686e-03, 1.56826654e-03,
       9.85382795e-01, 2.81667169e-02, 1.34070928e-04, 9.93079990e-02,
       5.06925583e-03, 3.99086770e-04, 1.66630372e-04, 2.23916446e-04,
       1.03501137e-03, 9.66946959e-01, 1.88308619e-02, 9.51628946e-03,
       2.63835071e-04, 1.41095603e-02, 4.96786134e-03, 5.59647568e-03,
       1.38090216e-02, 2.71635392e-04, 9.87494767e-01, 7.67735241e-04,
       1.08908778e-02, 2.44222097e-02, 4.95864151e-05, 1.27191818e-03,
       1.21602823e-03, 2.55686641e-02, 5.72015881e-04, 4.03959188e-04,
       1.68129476e-03, 8.52004596e-05, 1.89272519e-02, 4.22568672e-04,
       9.86967504e-01, 1.01776666e-03, 1.71902142e-02, 2.95494124e-03,
       1.91138894e-03, 9.68059804e-03], dtype=float32)

In [13]:
test_labels[0:5]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [15]:
score = model.evaluate(test_images, test_labels, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

Test loss: 0.009684167802333832
Test accuracy: 0.9437999725341797
